export function OrganizationJsonLd() {
    const jsonLd = {
        '@context': 'https://schema.org',
        '@type': 'Organization',
        '@id': 'https://www.ohakajimai-navi.jp/#organization',
        name: '株式会社清蓮',
        alternateName: ['お墓じまいナビ', 'Seiren'],
        description: 'お墓じまい・改葬・海洋散骨など供養に関わる実務を専門に行う会社。法令遵守を最優先に、全国対応でご家族の不安に寄り添います。',
        url: 'https://www.ohakajimai-navi.jp',
        logo: {
            '@type': 'ImageObject',
            url: 'https://www.ohakajimai-navi.jp/og-image.jpg',
        },
        image: 'https://www.ohakajimai-navi.jp/og-image.jpg',
        telephone: '0800-888-8788',
        email: 'contact@seiren.ne.jp',
        priceRange: 'お見積り無料',
        address: {
            '@type': 'PostalAddress',
            streetAddress: '戸塚町4170 高橋ビル1階',
            addressLocality: '横浜市戸塚区',
            addressRegion: '神奈川県',
            postalCode: '244-0003',
            addressCountry: 'JP',
        },
        geo: {
            '@type': 'GeoCoordinates',
            latitude: '35.3960962',
            longitude: '139.5300272',
        },
        contactPoint: [
            {
                '@type': 'ContactPoint',
                telephone: '045-881-9952',
                contactType: 'customer service',
                areaServed: { '@type': 'Country', name: '日本' },
                availableLanguage: 'Japanese',
                hoursAvailable: {
                    '@type': 'OpeningHoursSpecification',
                    dayOfWeek: [
                        'Monday', 'Tuesday', 'Wednesday', 'Thursday',
                        'Friday', 'Saturday', 'Sunday',
                    ],
                    opens: '09:00',
                    closes: '17:00',
                },
            },
            {
                '@type': 'ContactPoint',
                telephone: '0800-888-8788',
                contactType: 'customer service',
                contactOption: 'TollFree',
                areaServed: { '@type': 'Country', name: '日本' },
                availableLanguage: 'Japanese',
                hoursAvailable: {
                    '@type': 'OpeningHoursSpecification',
                    dayOfWeek: [
                        'Monday', 'Tuesday', 'Wednesday', 'Thursday',
                        'Friday', 'Saturday', 'Sunday',
                    ],
                    opens: '09:00',
                    closes: '17:00',
                },
            },
        ],
        subOrganization: {
            '@id': 'https://www.ohakajimai-navi.jp/#local-business',
        },
        areaServed: [
            { '@type': 'AdministrativeArea', name: '北海道' },
            { '@type': 'AdministrativeArea', name: '青森県' },
            { '@type': 'AdministrativeArea', name: '岩手県' },
            { '@type': 'AdministrativeArea', name: '宮城県' },
            { '@type': 'AdministrativeArea', name: '秋田県' },
            { '@type': 'AdministrativeArea', name: '山形県' },
            { '@type': 'AdministrativeArea', name: '福島県' },
            { '@type': 'AdministrativeArea', name: '茨城県' },
            { '@type': 'AdministrativeArea', name: '栃木県' },
            { '@type': 'AdministrativeArea', name: '群馬県' },
            { '@type': 'AdministrativeArea', name: '埼玉県' },
            { '@type': 'AdministrativeArea', name: '千葉県' },
            { '@type': 'AdministrativeArea', name: '東京都' },
            { '@type': 'AdministrativeArea', name: '神奈川県' },
            { '@type': 'AdministrativeArea', name: '新潟県' },
            { '@type': 'AdministrativeArea', name: '富山県' },
            { '@type': 'AdministrativeArea', name: '石川県' },
            { '@type': 'AdministrativeArea', name: '福井県' },
            { '@type': 'AdministrativeArea', name: '山梨県' },
            { '@type': 'AdministrativeArea', name: '長野県' },
            { '@type': 'AdministrativeArea', name: '岐阜県' },
            { '@type': 'AdministrativeArea', name: '静岡県' },
            { '@type': 'AdministrativeArea', name: '愛知県' },
            { '@type': 'AdministrativeArea', name: '三重県' },
            { '@type': 'AdministrativeArea', name: '滋賀県' },
            { '@type': 'AdministrativeArea', name: '京都府' },
            { '@type': 'AdministrativeArea', name: '大阪府' },
            { '@type': 'AdministrativeArea', name: '兵庫県' },
            { '@type': 'AdministrativeArea', name: '奈良県' },
            { '@type': 'AdministrativeArea', name: '和歌山県' },
            { '@type': 'AdministrativeArea', name: '鳥取県' },
            { '@type': 'AdministrativeArea', name: '島根県' },
            { '@type': 'AdministrativeArea', name: '岡山県' },
            { '@type': 'AdministrativeArea', name: '広島県' },
            { '@type': 'AdministrativeArea', name: '山口県' },
            { '@type': 'AdministrativeArea', name: '徳島県' },
            { '@type': 'AdministrativeArea', name: '香川県' },
            { '@type': 'AdministrativeArea', name: '愛媛県' },
            { '@type': 'AdministrativeArea', name: '高知県' },
            { '@type': 'AdministrativeArea', name: '福岡県' },
            { '@type': 'AdministrativeArea', name: '佐賀県' },
            { '@type': 'AdministrativeArea', name: '長崎県' },
            { '@type': 'AdministrativeArea', name: '熊本県' },
            { '@type': 'AdministrativeArea', name: '大分県' },
            { '@type': 'AdministrativeArea', name: '宮崎県' },
            { '@type': 'AdministrativeArea', name: '鹿児島県' },
            { '@type': 'AdministrativeArea', name: '沖縄県' },
            { '@type': 'Country', name: '日本' },
        ],
        serviceType: [
            'お墓じまい', '改葬', '海洋散骨', '墓石撤去', '遺骨供養',
            '改葬手続きサポート', '離檀交渉サポート', '洗骨', '粉骨',
        ],
        foundingDate: '2008-08-06',
        employee: {
            '@type': 'Person',
            name: '眞如 理恵',
            jobTitle: '代表取締役',
        },
        sameAs: [
            'https://line.me/R/ti/p/@956lieqb',
            'https://www.instagram.com/sankotu.cruise_seiren',
            'https://www.facebook.com/seirenjapan',
            'https://twitter.com/seiren_official',
            'https://www.google.com/maps/place/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE%E6%B8%85%E8%93%AE/@35.3960962,139.5274523,16z/data=!4m14!1m7!3m6!1s0x60185a9d066972b1:0xb59c13b10318f6c0!2z5qCq5byP5Lya56S-5riF6JOu!8m2!3d35.3960962!4d139.5300272!16s%2Fg%2F11h9vq64qd!3m5!1s0x60185a9d066972b1:0xb59c13b10318f6c0!8m2!3d35.3960962!4d139.5300272!16s%2Fg%2F11h9vq64qd?entry=ttu',
        ],
        hasOfferCatalog: {
            '@type': 'OfferCatalog',
            name: 'お墓じまいサービス一覧',
            itemListElement: [
                {
                    '@type': 'Offer',
                    name: '改葬手続きサポート',
                    description: '改葬許可申請に必要な書類の取得方法・記入ポイントをご案内',
                },
                {
                    '@type': 'Offer',
                    name: '墓石撤去工事',
                    description: '全国の提携石材店による墓石解体・撤去・整地',
                },
                {
                    '@type': 'Offer',
                    name: '海洋散骨',
                    description: '東京湾・相模湾などでの海洋散骨手配',
                },
                {
                    '@type': 'Offer',
                    name: '遺骨の洗骨・粉骨',
                    description: '取り出したご遺骨の洗骨・粉骨・容器への納め替え',
                },
            ],
        },
        knowsAbout: [
            '改葬手続き', 'お墓じまい', '墓石撤去工事', '離檀交渉',
            '海洋散骨', '粉骨', '洗骨', '永代供養', '改葬許可申請書',
        ],
    }

    return (
        <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
    )
}
